
# ========= Border =========
file_panel_border = '#dcdbd6'
sidebar_border = '#dcdbd6'
footer_border = '#dcdbd6'

# ========= Border Active =========
file_panel_border_active = '#a0997e'
sidebar_border_active = '#a0997e'
footer_border_active = '#a0997e'
modal_border_active = '#a0997e'

# ========= Background (bg) =========
full_screen_bg = '#232829'
file_panel_bg = '#232829'
sidebar_bg = '#232829'
footer_bg = '#232829'
modal_bg = '#232829'

# ========= Foreground (fg) =========
full_screen_fg = '#dcdbd6'
file_panel_fg = '#dcdbd6'
sidebar_fg = '#dcdbd6'
footer_fg = '#dcdbd6'
modal_fg = '#dcdbd6'

# ========= Special Color =========
cursor = '#dcdbd6'
correct = '#9cab8c'
error = '#a49e84'
hint = '#c1c5b0'
cancel = '#a49e84'
gradient_color = ['#232829', "#788587"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = '#232829'
file_panel_top_path = '#788587'
file_panel_item_selected_fg = '#788587'
file_panel_item_selected_bg = '#232829'

# ========= Sidebar Special Items =========
sidebar_title = '#dcdbd6'
sidebar_item_selected_fg = '#788587'
sidebar_item_selected_bg = '#232829'
sidebar_divider = '#dcdbd6'

# ========= Modal Special Items =========
modal_cancel_fg = "#383838"
modal_cancel_bg = '#a49e84'
modal_confirm_fg = "#383838"
modal_confirm_bg = '#9cab8c'
